spring.application.name=backupdb

spring.datasource.url=jdbc:postgresql://localhost:5432/backupdb
spring.datasource.username=postgres
spring.datasource.password=60301096

spring.datasource.driver-class-name=org.postgresql.Driver

# Para permitir o @Scheduled funcionar
spring.main.allow-bean-definition-overriding=true
spring.task.scheduling.pool.size=5
